spring:
  application:
    name: Api Transação

server:
  error:
    include-stacktrace: never
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  #server:
    #port: 7171

springdoc:
  show-actuator: true


